@Host = http://localhost:8080
@AccessToken = 일부로 "" 없습니다. 발급된 accessToken을 넣으세요
@RefreshToken = "발급된 refreshToken을 넣으세요"

### 로그인 (AccessToken 발급)

POST {{Host}}/login
Content-Type: application/json

{
    "username": "username",
    "password": "password"
}

### 데이터 생성

POST {{Host}}/todo
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
    "title": "test todo"
}

### 로그아웃

POST {{Host}}/logout
Authorization: Bearer {{AccessToken}}

### RefreshToken

POST {{Host}}/token/refresh
Content-Type: application/json

{
    "refresh_token": {{RefreshToken}}
}