// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Post {
  userId: number;
  id: number;
  title: string;
  body: string;
}
